apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: myapp2-rs
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: myapp2
    
  template: 
    metadata: # Dictionary
      name: myapp2-pod
      labels: # Dictionary
        app: myapp2  # Optional labels
  spec: 
    containers: # List
      - name: myapp-container
      - image: stacksimplify/kubenginx:2.0.0
        ports:
          - containerPort: 80 